name: Send Job Logs to mail

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: logsData
      continue-on-error: true
      run: |
       nohup node app.js &> logs.txt
    - name: output log file
      run: cat logs.txt
